animations { 
    enabled = false

    # Animation presets
    bezier = linear, 1, 1, 1, 1
    bezier = wind, 0.05, 0.69, 0.1, 1
    bezier = winIn, 0.1, 1.1, 0.1, 1
    bezier = winOut, 0.3, 1, 0, 1

    # # Fade animations
    animation = fadeIn, 1, 6, default
     
    # # Window animations
    animation = windowsMove, 1, 3, wind, slide
    animation = windowsIn, 1, 4, winIn, popin 99%
    animation = windowsOut, 1, 3, winOut, popin 95%

    # # Other animations
    # animation = layers, 0
    animation = workspaces, 1, 3, linear, fade
}

# Disable decorations & effects
decoration {
    # Blur configurations
    blur {
        enabled = true
        size = 5
        passes = 2
    }

    # Border radius
    rounding = 0
    rounding_power = 2

    # Active & inactive differentiator
    inactive_opacity = 0.8
    dim_inactive = false
    dim_strength = 0.3
}

decoration:shadow {
    # Lightweight dark shadows
    enabled = true
    range = 4
}

# Window decorations
general {

    # Monadtall
    layout = master

    # Optimized compositor settings
    allow_tearing = false

    # Window gaps
    gaps_in = 6
    gaps_out = 12

    # Border configuration (currently disabled)
    border_size = 0
    col.active_border = rgb(303334)
    col.inactive_border = rgba(1d2021cc)
}

# 60% estate for master window
master {
    new_status = master
    mfact = 0.50
}

# Layers
# layerrule = match:namespace ^(waybar)$, blur on

# Window rules
windowrule = match:float 1, rounding 5
# windowrule = match:focus 0, no_blur on

# Smart borders
workspace = w[t1], gapsout:0, gapsin:0, border:0, rounding:0, shadow:0
workspace = w[tg1], gapsout:0, gapsin:0, border:0, rounding:0, shadow:0
workspace = f[1], gapsout:0, gapsin:0, border:0, rounding:0, shadow:0
