general {
    # Monadtall
    layout = master
}

master {
    new_status = master
    mfact = 0.55
}

group {
    col.border_active = rgba(7daea3bf)
    col.border_inactive = rgba(40434480)
    groupbar {
        render_titles = false
        indicator_height = 3
        font_size = 15
        text_color = rgb(d4be98)
        col.active = rgb(404344)
        col.inactive = rgba(1d2021cc)
    }
}
