exec-once = rm ~/.cache/cliphist/db && cliphist.sh # Clipboard history
exec-once = power-saver.sh

# Startup applications
exec-once = waybar
exec-once = wbg ~/Pictures/backgrounds/castle.jpg
exec-once = mako
exec-once = hypridle
exec-once = swayosd-server
