#!/usr/bin/env dash

# Portal fixes
export XDG_SESSION_TYPE=wayland
export XDG_CURRENT_DESKTOP=river
export XDG_SESSION_DESKTOP=river
dbus-update-activation-environment --systemd \
    PATH \
    XDG_SESSION_TYPE \
    XDG_CURRENT_DESKTOP \
    XDG_SESSION_DESKTOP \
    WAYLAND_DISPLAY \
    DISPLAY

riverctl spawn 'waybar' # Status bar
riverctl rule-add -app-id "*" ssd # Global window decorations

# Layout generator
riverctl default-layout wideriver

for f in ~/.config/river/conf.d/*.sh; do
    [ -x "$f" ] && riverctl spawn "$f"
done
