#!/usr/bin/env dash
export XDG_CURRENT_DESKTOP=river

# Portal fixes
dbus-update-activation-environment --systemd XDG_CURRENT_DESKTOP XDG_SESSION_TYPE WAYLAND_DISPLAY DISPLAY
systemctl --user import-environment XDG_CURRENT_DESKTOP XDG_SESSION_TYPE WAYLAND_DISPLAY DISPLAY

# Status bar
riverctl spawn 'waybar'

# Layout generator
riverctl rule-add -app-id "*" ssd
riverctl default-layout wideriver
riverctl spawn 'wideriver \
    --border-width 2 \
    --border-color-focused 0x879251cc \
    --border-color-unfocused 0x56595acc \
    --layout left \
    --layout-alt monocle \
    --stack even \
    --count-master 1 \
    --ratio-master 0.55 \
    --inner-gaps 12 \
    --outer-gaps 12 \
    --smart-gaps \
    --border-width-smart-gaps 0 \
    --log-threshold info \
    > /tmp/wideriver.log 2>&1'

for f in ~/.config/river/conf.d/*.sh; do riverctl spawn "$f"; done
