#!/usr/bin/env dash
export XDG_CURRENT_DESKTOP=river

# Portal fixes
dbus-update-activation-environment --systemd XDG_CURRENT_DESKTOP XDG_SESSION_TYPE WAYLAND_DISPLAY DISPLAY
systemctl --user import-environment XDG_CURRENT_DESKTOP XDG_SESSION_TYPE WAYLAND_DISPLAY DISPLAY

# Status bar
riverctl spawn 'waybar'

# Layout generator
riverctl rule-add -app-id "*" ssd
riverctl default-layout wideriver

for f in ~/.config/river/conf.d/*.sh; do
    [ -x "$f" ] && riverctl spawn "$f"
done
